### ISSUE TITLE
Enforce sequential integer keys for Collections

### ISSUE THREAD

**Issue by osteel** [larastan/larastan#1535]
- Larastan Version: 2.4.0
- `--level` used: 7
- Pull request with failing test: N/A

### Description

Hi,

Apologies if that's been asked before, but is there a way to enforce sequential integer keys for Collections? Basically what [`list`](https://phpstan.org/writing-php-code/phpdoc-types#lists) does for arrays.

```php
// 1. Returns collect([0 => 'foo', 1 => 'bar', 2 => 'baz']) – desired behaviour ✅ 

/** @return Collection<int,string> */
public function test1(): Collection
{
    return collect(['foo', null, 'bar', 'baz', null])
        ->filter()
        ->values();
}

// 2. Returns collect([0 => 'foo', 2 => 'bar', 3 => 'baz']) – non-sequential, not spotted by PHPStan 🚫 

/** @return Collection<int,string> */
public function test2(): Collection
{
    return collect(['foo', null, 'bar', 'baz', null])
        ->filter();
}
```

Looking at the [stub](https://github.com/nunomaduro/larastan/blob/master/stubs/Collection.stub), I don't see a way to do it. Is it possible? Should it be added?

Thanks

**Comment by canvural** [comment]
> [0 => 'foo', 2 => 'bar', 3 => 'baz']

Is this also the result in runtime?

If this is only about `filter` it should be fixed somewhere here: https://github.com/nunomaduro/larastan/blob/master/src/ReturnTypes/CollectionFilterDynamicReturnTypeExtension.php

**Comment by osteel** [comment]
> Is this also the result in runtime?

Yes, because in `test2`, `values()` isn't called on the collection.

Basically what I want to achieve is using type-hinting to indicate that the returned collection should have sequential integer keys. So `test2` would be flagged by PHPStan as not being the case, and the developer would then remember to apply `values()` to the collection before returning.

Does that make sense?

**Comment by canvural** [comment]
Yeah I think this can be done. But only for the `filter` I don't know about other cases.

**Comment by philbates35** [comment]
@canvural @osteel I just came across this issue myself, IMO it feels like this needs to be something that can be applied to `Collection` as a whole and not-specific to `->filter()`. Something like one of the follow should gets across how I imagine this to work, though probably none of them are ideal and there might be a better way:

* `ListCollection<Foo>` (not sure how this would work with both eloquent collection and support collection :thinking:)
* `Collection<sequential-int, Foo>`
* `Collection<list, Foo>`
* `Collection<list<Foo>>`

Consider this snippet (using psudo-code `Collection<list, Foo>` syntax for the sake of example):

```php
/**
 * @return \Illuminate\Support\Collection<list, string>
 */
function foo()
{
    return new \Illuminate\Support\Collection([0 => 'some_string', 3 => 'some_other_string']);
}
```
If this behaviour was implemented in `->filter()` only as suggested in a previous comment phpstan would pass, but it should fail.

---

EDIT: Even better would be if `$listCollection->toArray()` and `$listCollection->all()` were type hinted to return a `list<Foo>`.

Probably worth mentioning the reason this is important is because I have a collection that is doing a `->filter()` where keys are persisted, the result of which is then json_encoded and returned in the API resulting in an JSON object instead of a JSON array because the keys aren't sequential. It does indeed highlight a missing test case, but still it would have been nice if phpstan would have highlighted it too.

**Comment by calebdw** [comment]
I think the best course of action would be a `sequential-int` type (with possible an optional starting value applied, e.g., `sequential-int<5>`, although I'm not sure if this would be useful).

However, this would probably be something that is better suited for PHPStan, thoughts @ondrejmirtes?

https://phpstan.org/writing-php-code/phpdoc-types#integer-ranges

**Comment by ondrejmirtes** [comment]
I have no idea what the behaviour should be and how to model this. As usual with proposals like this, I need to see some prior art in other programming languages.

**Comment by calebdw** [comment]
Hmmm, I'm not sure about the other programming languages...

However, more generally speaking, there's already the `list` type in PHPStan that is an array with sequential keys (essentially an `array<sequential-int, mixed>` in sticking with the above nomenclature). I was thinking that it would be useful to create the `sequential-int` type which could be applied to other objects as well.

**Comment by philbates35** [comment]
@ondrejmirtes To explain briefly in case you're unfamiliar with Laravel or Laravel collections -  Laravel's `Collection` classes are essentially just wrappers around a PHP array allowing developers to interact with the underlying array as an object. For example:

Vanilla PHP:
```php
/**
  * @return list<string>
  */
function getUsers(): array
{
    $users = ['phil', 'dave', 'john'];
    $upperUsers = array_map('ucfirst', $users);

    return array_filter($upperUsers, fn(string $name): bool => $name !== 'Dave');
}

getUsers();  // [0 => 'Phil', 2 => 'John']. phpstan fails because this is not a list
```
The same, but using Laravel collections:
```php
/**
  * @return  \Illuminate\Support\Collection<int, string>
  */
function getUsers(): \Illuminate\Support\Collection
{
    return (new \Illuminate\Support\Collection(['phil', 'dave', 'john']))
        ->map('ucfirst')
        ->filter(fn(string $name): bool => $name !== 'Dave');
}

getUsers() // \Illuminate\Support\Collection([0 => 'Phil', 2 => 'John']). phpstan passes and thinks this is fine
```
You can see there that because of the `->filter()` at the end of the collection version, that the keys are now not sequential and therefore the underlying array is no longer considered a `list`. The best we can do currently is `@return  \Illuminate\Support\Collection<int, string>` meaning the keys don't necessarily need to be sequential, meaning we can't guarantee that the collection is a "list collection" (i.e the underlying array is a `list`).

The end goal would be for either phpstan or larastan to introduce some syntax or a new "list collection" concept to get that second code snippet to result in a phpstan error due to the underlying collection not being a `list`.

Hope that clears things up a little.

**Comment by ondrejmirtes** [comment]
So you just want to disallow calling filter() on your Collection?

**Comment by philbates35** [comment]
@ondrejmirtes nope its more general than that, its just that `->filter()` is a common way that you end up with a collection with unexpected non-sequential keys. We'd be looking to have this fail too:

```php
/**
  * @return Collection<sequential-int, string>
  */
function getUsers(): \Illuminate\Support\Collection
{
    return new \Illuminate\Support\Collection([0 => 'phil', 2 => 'dave', 3 => 'john']);
}
```

Which is the collection-equivalent of how PHPStan would fail it we were using `list` without collections:

```php
/**
  * @return list<string>
  */
function getUsers(): array
{
    return [0 => 'phil', 2 => 'dave', 3 => 'john'];
}
```

In my mind, syntax more along the lines of `ListCollection<string>` seems more semantically correct than `Collection<sequential-int, string>`, but I don't know if its possible to have that syntax without `ListCollection` actually being implemented as a proper class in laravel/framework itself.

**Comment by calebdw** [comment]
I don't really care for `ListCollection` as there are so many collections (`SupportCollection`, `EloquentCollection`, `LazyCollection`, `Enumerable`, custom colletions, etc). Would you have to define a `List*` variant for each one?

**Comment by philbates35** [comment]
Yeah that's a fair point, probably reason enough for the `ListCollection` option to be a non-starter.

**Comment by philbates35** [comment]
If the generic type was updated from `Collection<TKey, TValue>` to `Collection<TArray>` where `TArray of array` I think that would allow this:

```
Collection<array<int, string>> // keys not necessarily sequential
Collection<list<string>> // keys have to be sequential
```
And the problem would be solved.

However that syntax will likely be annoying for the majority of users that just want to use a collection without caring about the key 🤔

**Comment by mad-briller** [comment]
> If the generic type was updated from `Collection<TKey, TValue>` to `Collection<TArray>` where `TArray of array` I think that would allow this:
> 
> ```
> Collection<array<int, string>> // keys not necessarily sequential
> Collection<list<string>> // keys have to be sequential
> ```
> 
> And the problem would be solved.
> 
> However that syntax will likely be annoying for the majority of users that just want to use a collection without caring about the key 🤔

this approach would have the benefit of allowing to use array shapes to describe collection shape too such as `Collection<array{foo: 1, bar: 2}>` but is a big breaking change so it's probably unlikely to ever happen :cry:

**Comment by calebdw** [comment]
Does `Collection{foo: 1, bar: 2}` not already work?

**Comment by mad-briller** [comment]
> Does `Collection{foo: 1, bar: 2}` not already work?

it does not because ObjectType doesn't accept shapes, only template types in the form of `<>` which `Collection` has defined as `Collection<TKey, TValue>`

the `{}` syntax is implemented for `array{}` only, the closest you can get is `Collection<'foo'|'bar', 1|2>` which loses the explicit mapping of key -> value unfortunately

**Comment by canvural** [comment]
I think currently this is a too far fetched and too niche of a request. I'm gonna close it now. It'd require some additions to PHPStan itself first. So, if in the future PHPStan has a way to express this, we can adopt it here.

Thanks for understanding.

**Comment by philbates35** [comment]
@canvural 

> It'd require some additions to PHPStan itself first. So, if in the future PHPStan has a way to express this, we can adopt it here.

If we took the approach outlined in https://github.com/larastan/larastan/issues/1535#issuecomment-1946804504 it wouldn't need any changes to PHPStan itself, though as discussed it would probably be a reasonably big breaking change - unless there's a way to say if `Collection<X>` form is used then assume `X of array`, otherwise is `Collection<X,Y>` form is used then fall back to how its used currently.
