### ISSUE TITLE
`view-string` not behaving as expected

### ISSUE THREAD

**Issue by JayBizzle** [larastan/larastan#1607]
- Larastan Version: 2.5.1
- `--level` used: 9

### Description
Perhaps I am not understanding correctly how this should work, but from what I have read, if I do something like...

```php
    /**
     * Display the data.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $data = [];

        return view('this-view-does-not-exist', ['data' => $data]);
    }
```

...Larastan should pick this up an throw an error because the view does not exist.

This doesn't seem to be the case.

I tested this with a fresh installation of Laravel 10 and the latest version of Larastan and no errors are reported when a view is missing.

I'm sure this worked as expected in earlier versions of Larastan. `2.2.7` is what we have just upgraded from.

Or have I misunderstood how the `view-string` type works?

Thanks

**Comment by szepeviktor** [comment]
We should have more tests.
https://github.com/nunomaduro/larastan/blob/master/tests/Type/data/view-exists.php

**Comment by JayBizzle** [comment]
So, are you saying it isn't working as expected?

**Comment by szepeviktor** [comment]
Larastan check `view` calls with 1 parameter only.
https://github.com/nunomaduro/larastan/blob/11bdd132565d37e808e4ac985a580b492c2d8887/src/Types/ViewStringType.php#L31-L36

Could you try with `return view('this-view-does-not-exist');`?

**Comment by szepeviktor** [comment]
I do not understand how it works. I'm just a janitor 🧹

**Comment by JayBizzle** [comment]
> Larastan check `view` calls with 1 string only.
> 
> https://github.com/nunomaduro/larastan/blob/11bdd132565d37e808e4ac985a580b492c2d8887/src/Types/ViewStringType.php#L31-L36
> 
> Could you try with `return view('this-view-does-not-exist');`?

Same result 😕

**Comment by NiclasvanEyk** [comment]
While working on my implementation on `route-name-string` in https://github.com/nunomaduro/larastan/pull/1734, I ran into a similar problem when trying to re-use the same logic as implemented by the `ViewStringType`.

In `ViewStringType.php` only the `accepts` method is overriden. The `acceptsWithReason` method which seems to be the 'new' way of implementing custom types is still using the implementation from `StringType`, which contains the following statement:

```php
        public function acceptsWithReason(Type $type, bool $strictTypes): AcceptsResult
	{
		if ($type instanceof self) {
			return AcceptsResult::createYes();
		}

		// ...
```

Components such as the `RuleLevelHelper`, which is e.g. used to check whether the argument type of a function call is accepted by the parameter type, only call `acceptsWithReason`. Therefore when checking if the string argument passed to `view('non-existing-view')`, `ViewStringType::acceptsWithReason` is called, which delegates to `StringType::acceptsWithReason`. Since the argument to `view` is a string, the check `$type instanceof self` yields `true`, so now every `string` is also accepted by parameters declared as `view-string`, leading to the problems described in this issue.

A possible solution is to implement the logic that currently lives in `ViewString::accepts` in a new overridden `ViewString::acceptsWithReason`, moving all `TrinaryLogic` to `AcceptanceResult` and delegate `ViewString::accepts` to `ViewString::acceptsWithReason()->result`, similar to how it is done in `StringType::accepts`.

**Comment by canvural** [comment]
I believe this was fixed in newer releases. Thank you!
